table constructor_standings
	lineageTag: c8463e6d-d3d7-4cc3-b760-6efb7929a750

	column constructorStandingsId
		dataType: int64
		formatString: 0
		lineageTag: 9d3f7934-d969-4b63-94ee-2d3f01ab2377
		summarizeBy: count
		sourceColumn: constructorStandingsId

		annotation SummarizationSetBy = Automatic

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: 2c5fd454-9342-4ae9-a34b-a64a9577462c
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column constructorId
		dataType: int64
		formatString: 0
		lineageTag: 6d13640e-919c-470b-8b3b-2a11e4854591
		summarizeBy: none
		sourceColumn: constructorId

		annotation SummarizationSetBy = Automatic

	column points
		dataType: int64
		formatString: 0
		lineageTag: 6c41127b-d2fd-49c2-804d-7909b2a543e6
		summarizeBy: sum
		sourceColumn: points

		annotation SummarizationSetBy = Automatic

	column position
		dataType: int64
		formatString: 0
		lineageTag: efc26aab-681b-47f7-80be-305b7ac95ad8
		summarizeBy: sum
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column positionText
		dataType: string
		lineageTag: 91998f2c-c16d-4dff-81f0-6092f3949565
		summarizeBy: none
		sourceColumn: positionText

		annotation SummarizationSetBy = Automatic

	column wins
		dataType: int64
		formatString: 0
		lineageTag: aba3ca2d-dad9-4d50-a432-0b932b6e8719
		summarizeBy: sum
		sourceColumn: wins

		annotation SummarizationSetBy = Automatic

	partition constructor_standings-020fc438-585c-4710-80ed-4a9f928d53c0 = m
		mode: import
		queryGroup: Raw
		source =
				let
				    SharepointFolder = CSV_FilePath,
				    FileName = "constructor_standings.csv",
				    FileToImport = SharepointFolder & FileName ,
				    Source = Csv.Document(Web.Contents(FileToImport ),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"constructorStandingsId", Int64.Type}, {"raceId", Int64.Type}, {"constructorId", Int64.Type}, {"points", Int64.Type}, {"position", Int64.Type}, {"wins", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

