table seasons
	lineageTag: 3164e4f0-f6b2-4f7d-b453-4ac6a99dcbf9

	column year
		dataType: int64
		formatString: 0
		lineageTag: b01a9df0-b7e4-4059-a4ec-760d7d8883d5
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: a152999e-9407-4b5c-bf2a-a178814414e0
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	partition seasons-6e2bae6d-e289-4464-869a-85fa42626d1c = m
		mode: import
		queryGroup: Raw
		source =
				let
				    Source = Csv.Document(Web.Contents(CSV_FilePath & "seasons.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"year", Int64.Type}, {"url", type text}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"year", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

